<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="$(SolutionDir)\_Common\CommonProject.props" />
	
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="nunit" />
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CheckReceiptSDK\CheckReceiptSDK.csproj" />
	</ItemGroup>
</Project>